#include "binary.h"
#include <stdio.h>
#include <stdint.h>
#include <inttypes.h>
#define BYTES_PER_LINE (32)

int binary_main(int argc, char** args)
{
    char *array_name = args[2];
    char *in_file = args[3];
    char *out_file = args[4];
    FILE *fin = fopen(in_file, "rb");
    if(!fin) {
        printf("%s: error opening file %s for read\n", args[0], in_file);
        return 2;
    }
    FILE *fout = fopen(out_file, "wb");
    if(!fout) {
        printf("%s: error opening file %s for write\n", args[1], out_file);
        return 2;
    }
    fprintf(fout, "%s\n", "/* AUTOGENERATED HEADER using txt2h bin mode - Callum McGing */");
    fprintf(fout, "#ifndef BIN_HEADER_%s\n", array_name);
    fprintf(fout, "#define BIN_HEADER_%s\n", array_name);
    fprintf(fout, "const unsigned char %s[] = {\n", array_name);
    unsigned char buffer[BYTES_PER_LINE];
    int read;
    uint64_t count = 0;
    while((read = fread(buffer, 1, BYTES_PER_LINE, fin))) {
        fprintf(fout, "   ");
        for(int i = 0; i < read; i++) {
            if(i + 1 == read && read < BYTES_PER_LINE) {
                fprintf(fout, "0x%02X", buffer[i]);
            } else {
                fprintf(fout, " 0x%02X,", buffer[i]);
            }
        }
        count += read;
        fprintf(fout, "\n");
    }
    fprintf(fout, "};\n");
    fprintf(fout, "#define %s_len (%"PRIu64")\n", array_name, count);
    fprintf(fout, "#endif");
    return 0;
}